CLASS ZCL_CSV_FORMATTER DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES ZIF_FILE_FORMATTER.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS ZCL_CSV_FORMATTER IMPLEMENTATION.

  METHOD ZIF_FILE_FORMATTER~GENERATE.
    RS_RESULT-EXTENSION = 'csv'.
    RS_RESULT-MIME_TYPE = 'text/csv'.

    DATA LV_CSV TYPE STRING.

    " Dereference the data table
    FIELD-SYMBOLS <LT_DATA> TYPE STANDARD TABLE.
    ASSIGN IR_DATA->* TO <LT_DATA>.

    DATA LT_COL_META TYPE ZIF_FILE_FORMATTER=>TT_COL_META.
    LT_COL_META = IT_COL_META.

    IF LT_COL_META IS INITIAL.
      TRY.
          DATA(LO_TD) = CAST CL_ABAP_TABLEDESCR( CL_ABAP_TYPEDESCR=>DESCRIBE_BY_DATA( <LT_DATA> ) ).
          DATA(LO_SD) = CAST CL_ABAP_STRUCTDESCR( LO_TD->GET_TABLE_LINE_TYPE( ) ).
          LOOP AT LO_SD->COMPONENTS INTO DATA(LS_COMP).
            APPEND VALUE #( NAME = LS_COMP-NAME ) TO LT_COL_META.
          ENDLOOP.
        CATCH CX_ROOT.
      ENDTRY.
    ENDIF.

    " ── Header row ──
    DATA LV_HDR TYPE STRING.
    LOOP AT LT_COL_META INTO DATA(LS_HCOMP).
      IF LV_HDR IS NOT INITIAL. LV_HDR = LV_HDR && ','. ENDIF.
      LV_HDR = LV_HDR && LS_HCOMP-NAME.
    ENDLOOP.
    LV_CSV = LV_HDR && CL_ABAP_CHAR_UTILITIES=>CR_LF.

    " ── Data rows ──
    LOOP AT <LT_DATA> ASSIGNING FIELD-SYMBOL(<LS_ROW>).
      DATA LV_DROW TYPE STRING.
      CLEAR LV_DROW.
      LOOP AT LT_COL_META INTO DATA(LS_DCOMP).
        IF LV_DROW IS NOT INITIAL. LV_DROW = LV_DROW && ','. ENDIF.
        ASSIGN COMPONENT LS_DCOMP-NAME OF STRUCTURE <LS_ROW> TO FIELD-SYMBOL(<LV_VAL>).
        IF SY-SUBRC = 0. LV_DROW = LV_DROW && |{ <LV_VAL> }|. ENDIF.
      ENDLOOP.
      LV_CSV = LV_CSV && LV_DROW && CL_ABAP_CHAR_UTILITIES=>CR_LF.
    ENDLOOP.

    RS_RESULT-XSTRING = CL_ABAP_CONV_CODEPAGE=>CREATE_OUT( CODEPAGE = `UTF-8` )->CONVERT( LV_CSV ).
  ENDMETHOD.

ENDCLASS.

