CLASS ZCL_JOB_BUSINESS_LOGIC DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    INTERFACES IF_APJ_DT_EXEC_OBJECT.
    INTERFACES IF_APJ_RT_EXEC_OBJECT.
    INTERFACES IF_APJ_RT_JOB_NOTIF_EXIT.

  PROTECTED SECTION.
  PRIVATE SECTION.

    " Instance state
    DATA MV_JOB_UUID_STR    TYPE STRING.
    DATA MV_JOB_ID      TYPE ZDRS_JOB_CONFIG-JOB_ID.
    DATA MV_JOB_UUID    TYPE ZDRS_JOB_CONFIG-JOB_UUID.
    DATA MV_SUBSCR_ID   TYPE ZDRS_JOB_CONFIG-SUBSCR_ID.
    DATA MV_TMZONE      TYPE TIMEZONE.
    DATA MV_DATE        TYPE D.
    DATA MV_T_LOCAL     TYPE T.

    " Job Log Instance
    DATA MV_JOB_HIST_UUID TYPE SYSUUID_X16.
    DATA MS_JOB_INFO TYPE IF_APJ_RT_JOB_NOTIF_EXIT=>TS_JOB_STEP_INFO.
    DATA MV_JOB_CATALOG  TYPE APJ_JOB_CATALOG_ENTRY_NAME.
    DATA MV_JOB_TEMPLATE TYPE APJ_JOB_TEMPLATE_NAME.
    DATA MV_JOB_COUNT  TYPE TBTCM-JOBCOUNT.
    DATA MV_JOB_NAME TYPE TBTCM-JOBNAME.

    METHODS PARSE_PARAMETERS
      IMPORTING IT_PARAMETERS TYPE IF_APJ_RT_EXEC_OBJECT=>TT_TEMPL_VAL.

    METHODS FIND_JOB_RECORD
      RETURNING VALUE(RV_FOUND) TYPE ABAP_BOOL
      RAISING   CX_APJ_RT.

    METHODS PROCESS_SUBSCRSCRIPTION
      RAISING CX_APJ_RT.

    METHODS CREATE_REPORT
      IMPORTING IS_PARAMS        TYPE ZIF_REPORT=>TY_PARAMS
      RETURNING VALUE(RO_REPORT) TYPE REF TO ZIF_REPORT
      RAISING   CX_APJ_RT..

    METHODS IS_DUPLICATE
      RETURNING VALUE(RV_RESULT) TYPE ABAP_BOOL.

    METHODS STORE_FILE
      IMPORTING IV_XSTRING        TYPE XSTRING
                IV_EXTENSION      TYPE STRING
                IV_MIME_TYPE      TYPE STRING
                IV_PREFIX         TYPE STRING
      EXPORTING EV_FILE_UUID      TYPE ZDRS_FILE-FILE_UUID
      RETURNING VALUE(RV_SUCCESS) TYPE ABAP_BOOL
      RAISING   CX_APJ_RT.

ENDCLASS.


CLASS ZCL_JOB_BUSINESS_LOGIC IMPLEMENTATION.

  METHOD IF_APJ_DT_EXEC_OBJECT~GET_PARAMETERS.
    ET_PARAMETER_DEF = VALUE #(
      DATATYPE       = 'C'
      CHANGEABLE_IND = ABAP_TRUE
      ( SELNAME       = 'JOB_UUID'
        KIND          = IF_APJ_DT_EXEC_OBJECT=>PARAMETER
        PARAM_TEXT    = 'Job UUID'
        LENGTH        = 32
        LOWERCASE_IND = ABAP_TRUE
        MANDATORY_IND = ABAP_FALSE )
      ( SELNAME       = 'JOB_ID'
        KIND          = IF_APJ_DT_EXEC_OBJECT=>PARAMETER
        PARAM_TEXT    = 'Job ID'
        LENGTH        = 12
        LOWERCASE_IND = ABAP_FALSE
        MANDATORY_IND = ABAP_FALSE )
    ).
  ENDMETHOD.


  METHOD IF_APJ_RT_EXEC_OBJECT~EXECUTE.
    " Clear instance state for reuse
    CLEAR: MV_JOB_UUID_STR, MV_JOB_ID, MV_JOB_UUID, MV_SUBSCR_ID,
           MV_TMZONE, MV_DATE, MV_T_LOCAL, MV_JOB_HIST_UUID,
           MS_JOB_INFO, MV_JOB_CATALOG, MV_JOB_TEMPLATE,
           MV_JOB_COUNT, MV_JOB_NAME.

    " STEP 1: Parse job parameters
    PARSE_PARAMETERS( IT_PARAMETERS ).

    " STEP 2: Resolve job record from DB
    IF FIND_JOB_RECORD( ) = ABAP_FALSE.
      " Message: Job configuration not found
      RAISE EXCEPTION TYPE CX_APJ_RT
        MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
        TYPE 'E'
        NUMBER '026'.
    ENDIF.

    CALL FUNCTION 'GET_JOB_RUNTIME_INFO'
      IMPORTING
        JOBCOUNT          = MV_JOB_COUNT
        JOBNAME           = MV_JOB_NAME
        JOB_CATALOG_ENTRY = MV_JOB_CATALOG
        JOB_TEMPLATE_NAME = MV_JOB_TEMPLATE
      EXCEPTIONS
        NO_RUNTIME_INFO   = 1.

    IF SY-SUBRC <> 0.
      MV_JOB_NAME = 'TEST_JOB'.
      MV_JOB_COUNT = '00000000'.
    ENDIF.

    MS_JOB_INFO-JOB_NAME  = MV_JOB_NAME.
    MS_JOB_INFO-JOB_COUNT = MV_JOB_COUNT.

    SELECT SINGLE REPORT_ID FROM ZDRS_SUBSCR
     WHERE SUBSCR_ID = @MV_SUBSCR_ID
     INTO @DATA(LV_REPORT_ID).

    IF SY-SUBRC <> 0.
      " Message: Subscription not found
      RAISE EXCEPTION TYPE CX_APJ_RT
        MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
        TYPE 'E'
        NUMBER '027'.
    ENDIF.

    MV_JOB_HIST_UUID = ZCL_JOB_LOG=>GET_INSTANCE( )->LOG_JOB_START(
        IS_JOB_INFO               = MS_JOB_INFO
        IV_JOB_CATALOG_ENTRY_NAME = MV_JOB_CATALOG
        IV_JOB_TEMPLATE_NAME      = MV_JOB_TEMPLATE
        IV_JOB_CONFIG_UUID        = MV_JOB_UUID
        IV_REPORT_ID              = LV_REPORT_ID
        IV_USER = CONV #( CL_ABAP_CONTEXT_INFO=>GET_USER_TECHNICAL_NAME( ) )
    ).

    " STEP 3: Resolve local date/time for file naming
    DATA LV_TS_NOW TYPE TIMESTAMPL.
    GET TIME STAMP FIELD LV_TS_NOW.
    CONVERT TIME STAMP LV_TS_NOW TIME ZONE MV_TMZONE
      INTO DATE MV_DATE TIME MV_T_LOCAL.

    TRY.

        " Execute report, store file, and send email
        PROCESS_SUBSCRSCRIPTION( ).
        " If execution succeeds without exceptions, set status to Finished (F)
        IF MV_JOB_HIST_UUID IS NOT INITIAL.
          ZCL_JOB_LOG=>GET_INSTANCE( )->LOG_JOB_END(
            IV_JOB_HIST_UUID = MV_JOB_HIST_UUID
            IV_JOB_STATUS    = 'F'
          ).
        ENDIF.
        " Catch all application-level exceptions and dumps
      CATCH CX_ROOT INTO DATA(LX_ERROR).
        " Safely capture the error state
        IF MV_JOB_HIST_UUID IS NOT INITIAL.
          ZCL_JOB_LOG=>GET_INSTANCE( )->LOG_JOB_END(
            IV_JOB_HIST_UUID = MV_JOB_HIST_UUID
            IV_JOB_STATUS    = 'A'
            IV_MESSAGE       = LX_ERROR->GET_TEXT( )
          ).
        ENDIF.

        " Re-raise the exception using custom message class for Fiori
        DATA(LV_ERR_TXT) = LX_ERROR->GET_TEXT( ).
        DATA(LV_MSGV1)   = CONV SYMSGV( LV_ERR_TXT+0(50) ).

        " Message: Job execution failed: &1
        RAISE EXCEPTION TYPE CX_APJ_RT
          MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
          TYPE 'E'
          NUMBER '000'
          WITH LV_MSGV1
          EXPORTING
            PREVIOUS = LX_ERROR.

    ENDTRY.

  ENDMETHOD.


  METHOD IF_APJ_RT_JOB_NOTIF_EXIT~NOTIFY_JT_START.
    " This method is not called by the standard APJ framework
  ENDMETHOD.


  METHOD IF_APJ_RT_JOB_NOTIF_EXIT~NOTIFY_JT_END.
    " The framework only calls this method implicitly when the job is aborted
    DATA LV_JOB_HIST_UUID TYPE SYSUUID_X16.

    IF MV_JOB_HIST_UUID IS NOT INITIAL.
      LV_JOB_HIST_UUID = MV_JOB_HIST_UUID.
    ELSE.
      SELECT SINGLE JOB_HIST_UUID FROM ZDRS_JOB_HISTORY
        WHERE JOB_NAME = @IS_JOB_INFO-JOB_NAME
          AND JOB_COUNT = @IS_JOB_INFO-JOB_COUNT
        INTO @LV_JOB_HIST_UUID.

      IF SY-SUBRC <> 0.
        " Message: Job history record not found
        RAISE EXCEPTION TYPE CX_APJ_RT
          MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
          TYPE 'E'
          NUMBER '028'.
      ENDIF.
    ENDIF.

    IF LV_JOB_HIST_UUID IS NOT INITIAL.
      ZCL_JOB_LOG=>GET_INSTANCE( )->LOG_JOB_END(
        IV_JOB_HIST_UUID = LV_JOB_HIST_UUID
        IV_STEP_STATUS   = IV_STEP_STATUS
        IV_JOB_STATUS    = IV_JOB_STATUS
      ).
    ENDIF.
  ENDMETHOD.


  METHOD PARSE_PARAMETERS.
    LOOP AT IT_PARAMETERS INTO DATA(LS_PARAMETER).
      CASE LS_PARAMETER-SELNAME.
        WHEN 'JOB_UUID'. MV_JOB_UUID_STR = LS_PARAMETER-LOW.
        WHEN 'JOB_ID'.   MV_JOB_ID   = LS_PARAMETER-LOW.
      ENDCASE.
    ENDLOOP.
  ENDMETHOD.


  METHOD FIND_JOB_RECORD.
    IF MV_JOB_UUID_STR IS NOT INITIAL.
      TRY.
          " Convert UUID from String (passed from Job Parameters) to RAW16 (Internal ABAP format for DB query)
          MV_JOB_UUID = CONV #( MV_JOB_UUID_STR ).
        CATCH CX_ROOT.
          CLEAR MV_JOB_UUID.
      ENDTRY.

      IF MV_JOB_UUID IS NOT INITIAL.
        SELECT SINGLE SUBSCR_ID, TMZONE
          FROM ZDRS_JOB_CONFIG
          WHERE JOB_UUID = @MV_JOB_UUID
          INTO ( @MV_SUBSCR_ID, @MV_TMZONE ).

        IF SY-SUBRC <> 0.
          " Message: Job configuration not found by UUID
          RAISE EXCEPTION TYPE CX_APJ_RT
            MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
            TYPE 'E'
            NUMBER '029'.
        ENDIF.
      ENDIF.
    ENDIF.

    IF MV_JOB_UUID IS INITIAL AND MV_JOB_ID IS NOT INITIAL.
      SELECT SINGLE JOB_UUID, SUBSCR_ID, TMZONE
        FROM ZDRS_JOB_CONFIG
        WHERE JOB_ID = @MV_JOB_ID
        INTO ( @MV_JOB_UUID, @MV_SUBSCR_ID, @MV_TMZONE ).

      IF SY-SUBRC <> 0.
        " Message: Job configuration not found by ID
        RAISE EXCEPTION TYPE CX_APJ_RT
          MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
          TYPE 'E'
          NUMBER '030'.
      ENDIF.
    ENDIF.

    IF MV_TMZONE IS INITIAL.
      MV_TMZONE = 'UTC'.
    ENDIF.

    RV_FOUND = COND #( WHEN MV_JOB_UUID IS NOT INITIAL
                       THEN ABAP_TRUE ELSE ABAP_FALSE ).
  ENDMETHOD.


  METHOD PROCESS_SUBSCRSCRIPTION.
    SELECT SINGLE REPORT_ID, OUTPUT_FORMAT, EMAIL_CC, EMAIL_TO, SUBSCR_UUID, CREATED_BY
      FROM ZDRS_SUBSCR
      WHERE SUBSCR_ID = @MV_SUBSCR_ID
      INTO @DATA(LS_SUBSCR).

    IF SY-SUBRC <> 0.
      " Message: Subscription not found
      RAISE EXCEPTION TYPE CX_APJ_RT
        MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
        TYPE 'E'
        NUMBER '027'.
    ENDIF.

    DATA(LO_MANAGER_EMAIL) = NEW ZCL_MANAGER_EMAIL( ).

    DATA LS_PARAMS TYPE ZIF_REPORT=>TY_PARAMS.
    LS_PARAMS-SUBSCR_UUID   = LS_SUBSCR-SUBSCR_UUID.
    LS_PARAMS-REPORT_ID     = LS_SUBSCR-REPORT_ID.
    LS_PARAMS-OUTPUT_FORMAT = LS_SUBSCR-OUTPUT_FORMAT.

    DATA(LO_REPORT) = CREATE_REPORT( LS_PARAMS ).
    IF LO_REPORT IS NOT BOUND.

      MESSAGE ID 'ZMSG_DRS_SP26_SAP01' TYPE 'E' NUMBER '031' INTO DATA(LV_MSG_031).
      LO_MANAGER_EMAIL->SEND_ERROR_EMAIL(
          IV_JOB_UUID  = MV_JOB_UUID
          IV_REPORT_ID = LS_SUBSCR-REPORT_ID
          IV_CREATED_BY = LS_SUBSCR-CREATED_BY
          IV_ERROR_MSG = CONV #( LV_MSG_031 )
      ).

      " Message: Failed to initialize report class
      RAISE EXCEPTION TYPE CX_APJ_RT
        MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
        TYPE 'E'
        NUMBER '031'.
    ENDIF.

    IF IS_DUPLICATE( ) = ABAP_TRUE.
      RETURN.
    ENDIF.

    DATA LS_RESULT TYPE ZIF_REPORT=>TY_RESULT.
    TRY.
        LS_RESULT = LO_REPORT->EXECUTE( ).
      CATCH CX_SY_CREATE_OBJECT_ERROR INTO DATA(LX_OBJ_ERR).

        MESSAGE ID 'ZMSG_DRS_SP26_SAP01' TYPE 'E' NUMBER '032' INTO DATA(LV_MSG_032).
        LO_MANAGER_EMAIL->SEND_ERROR_EMAIL(
            IV_JOB_UUID  = MV_JOB_UUID
            IV_REPORT_ID = LS_SUBSCR-REPORT_ID
            IV_CREATED_BY = LS_SUBSCR-CREATED_BY
            IV_ERROR_MSG = CONV #( LV_MSG_032 )
        ).

        " Message: Execution of report failed
        RAISE EXCEPTION TYPE CX_APJ_RT
          MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
          TYPE 'E'
          NUMBER '032'
          EXPORTING
            PREVIOUS = LX_OBJ_ERR.
    ENDTRY.

    DATA LV_FILE_UUID TYPE ZDRS_FILE-FILE_UUID.

    DATA(LV_STORE_SUCCESS) = STORE_FILE(
      EXPORTING
        IV_XSTRING   = LS_RESULT-XSTRING
        IV_EXTENSION = LS_RESULT-EXTENSION
        IV_MIME_TYPE = LS_RESULT-MIME_TYPE
        IV_PREFIX    = LS_RESULT-FILE_NAME_PREFIX
      IMPORTING
        EV_FILE_UUID = LV_FILE_UUID
    ).

    IF LV_STORE_SUCCESS = ABAP_TRUE.
      ZCL_JOB_LOG=>GET_INSTANCE( )->UPDATE_JOB_RESULTS(
          IV_JOB_HIST_UUID = MV_JOB_HIST_UUID
          IV_FILE_UUID     = LV_FILE_UUID
          IV_OUTPUT_FORMAT = LS_SUBSCR-OUTPUT_FORMAT
      ).

      LO_MANAGER_EMAIL->SEND_EMAIL(
          IV_JOB_UUID      = MV_JOB_UUID
          IV_REPORT_ID     = LS_SUBSCR-REPORT_ID
          IV_OUTPUT_FORMAT = LS_SUBSCR-OUTPUT_FORMAT
          IV_FILE_CONTENT  = LS_RESULT-XSTRING
          IV_FILE_NAME     = CONV #( LS_RESULT-FILE_NAME_PREFIX )
          IV_CREATED_BY    = LS_SUBSCR-CREATED_BY
          IV_EMAIL_TO      = CONV #( LS_SUBSCR-EMAIL_TO )
          IV_EMAIL_CC      = CONV #( LS_SUBSCR-EMAIL_CC )
      ).
    ELSE.
      MESSAGE ID 'ZMSG_DRS_SP26_SAP01' TYPE 'E' NUMBER '034' INTO DATA(LV_MSG_034).
      LO_MANAGER_EMAIL->SEND_ERROR_EMAIL(
          IV_JOB_UUID  = MV_JOB_UUID
          IV_REPORT_ID = LS_SUBSCR-REPORT_ID
          IV_CREATED_BY = LS_SUBSCR-CREATED_BY
          IV_ERROR_MSG = CONV #( LV_MSG_034 )
      ).
    ENDIF.
  ENDMETHOD.


  METHOD CREATE_REPORT.
    RO_REPORT = ZCL_REPORT_FACTORY=>CREATE(
      IV_REPORT_ID = IS_PARAMS-REPORT_ID
      IS_PARAMS    = IS_PARAMS
    ).
  ENDMETHOD.


  METHOD IS_DUPLICATE.
    DATA LV_CUTOFF TYPE TIMESTAMPL.
    DATA LV_COUNT TYPE I.

    GET TIME STAMP FIELD LV_CUTOFF.
    LV_CUTOFF = CL_ABAP_TSTMP=>SUBTRACTSECS(
                  TSTMP = LV_CUTOFF
                  SECS  = 30 ).

    SELECT COUNT(*) FROM ZDRS_FILE
      WHERE JOB_UUID = @MV_JOB_UUID
        AND CREATED_AT  >= @LV_CUTOFF
      INTO @LV_COUNT.

    RV_RESULT = COND #( WHEN LV_COUNT > 0 THEN ABAP_TRUE ELSE ABAP_FALSE ).
  ENDMETHOD.


  METHOD STORE_FILE.
    RV_SUCCESS = ABAP_FALSE.

    DATA(LV_HHMM)      = |{ MV_T_LOCAL+0(2) }{ MV_T_LOCAL+2(2) }|.
    DATA(LV_FILE_NAME) = |{ IV_PREFIX }_{ MV_DATE }_{ LV_HHMM }_{ MV_TMZONE }.{ IV_EXTENSION }|.

    DATA LV_TIMESTAMP TYPE TIMESTAMPL.
    GET TIME STAMP FIELD LV_TIMESTAMP.

    DATA LV_FILE_UUID TYPE ZDRS_FILE-FILE_UUID.
    TRY.
        LV_FILE_UUID = CL_SYSTEM_UUID=>CREATE_UUID_X16_STATIC( ).
      CATCH CX_UUID_ERROR INTO DATA(LX_UUID_ERR).
        " Message: Failed to generate UUID
        RAISE EXCEPTION TYPE CX_APJ_RT
          MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
          TYPE 'E'
          NUMBER '033'
          EXPORTING
            PREVIOUS = LX_UUID_ERR.
    ENDTRY.

    DATA(LV_BYTES) = XSTRLEN( IV_XSTRING ).
    DATA LV_FILE_SIZE_DISP TYPE ZDRS_FILE-FILE_SIZE_DISPLAY.

    IF LV_BYTES < 1024.
      LV_FILE_SIZE_DISP = |{ LV_BYTES } B|.
    ELSEIF LV_BYTES < 1048576. " 1024 * 1024
      DATA(LV_KB) = LV_BYTES / 1024.
      LV_FILE_SIZE_DISP = |{ LV_KB DECIMALS = 2 } KB|.
    ELSE.
      DATA(LV_MB) = LV_BYTES / 1048576.
      LV_FILE_SIZE_DISP = |{ LV_MB DECIMALS = 2 } MB|.
    ENDIF.

    DATA(LS_FILE) = VALUE ZDRS_FILE(
      FILE_UUID    = LV_FILE_UUID
      JOB_UUID     = MV_JOB_UUID
      FILE_NAME    = LV_FILE_NAME
      MIME_TYPE    = IV_MIME_TYPE
      FILE_SIZE    = XSTRLEN( IV_XSTRING )
      FILE_SIZE_DISPLAY = LV_FILE_SIZE_DISP
      FILE_CONTENT = IV_XSTRING
      CREATED_BY   = CL_ABAP_CONTEXT_INFO=>GET_USER_TECHNICAL_NAME( )
      CREATED_AT   = LV_TIMESTAMP
    ).

    INSERT ZDRS_FILE FROM @LS_FILE.
    IF SY-SUBRC <> 0.
      ROLLBACK WORK.
      " Message: Failed to store file to database
      RAISE EXCEPTION TYPE CX_APJ_RT
        MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
        TYPE 'E'
        NUMBER '034'.
    ENDIF.

    RV_SUCCESS = ABAP_TRUE.
    EV_FILE_UUID = LV_FILE_UUID.
  ENDMETHOD.

ENDCLASS.

