CLASS ZCL_REPORT_FACTORY DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS CREATE
      IMPORTING IV_REPORT_ID     TYPE ZDRS_SUBSCR-REPORT_ID
                IS_PARAMS        TYPE ZIF_REPORT=>TY_PARAMS
      RETURNING VALUE(RO_REPORT) TYPE REF TO ZIF_REPORT.

  PRIVATE SECTION.
    CLASS-METHODS GET_REPORT_CLASS
      IMPORTING IV_REPORT_ID         TYPE ZDRS_SUBSCR-REPORT_ID
      RETURNING VALUE(RV_CLASS_NAME) TYPE CLASSNAME.
ENDCLASS.

CLASS ZCL_REPORT_FACTORY IMPLEMENTATION.
  METHOD CREATE.
    " 1. Lookup class name from registry
    DATA(LV_CLASS_NAME) = GET_REPORT_CLASS( IV_REPORT_ID ).

    " 2. Guard against invalid configuration
    IF LV_CLASS_NAME IS INITIAL.
      RETURN.
    ENDIF.

    " 3. Dynamic instantiation
    DATA LO_REPORT TYPE REF TO OBJECT.
    TRY.
        CREATE OBJECT LO_REPORT TYPE (LV_CLASS_NAME)
          EXPORTING IS_PARAMS = IS_PARAMS.
      CATCH CX_SY_CREATE_OBJECT_ERROR.
        RETURN. " Handle instantiation errors gracefully
    ENDTRY.

    " 4. Cast to target interface
    RO_REPORT ?= LO_REPORT.
  ENDMETHOD.

  METHOD GET_REPORT_CLASS.
    SELECT SINGLE REPORT_CLASS
      FROM ZDRS_RP_REGISTRY
      WHERE REPORT_ID = @IV_REPORT_ID
        AND IS_ACTIVE = @ABAP_TRUE
      INTO @RV_CLASS_NAME.

    " Fallback for test/demo if registry table is empty during initial setup:
    IF SY-SUBRC <> 0 AND IV_REPORT_ID = 'GL-01'.
      RV_CLASS_NAME = 'ZCL_REPORT_GL01'.
    ENDIF.
  ENDMETHOD.
ENDCLASS.

