CLASS ZCL_FORMATTER_FACTORY DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS CREATE
      IMPORTING IV_OUTPUT_FORMAT        TYPE STRING " Maps to CHAR(4) field FILE_TYPE
      RETURNING VALUE(RO_FORMATTER) TYPE REF TO ZIF_FILE_FORMATTER.
ENDCLASS.

CLASS ZCL_FORMATTER_FACTORY IMPLEMENTATION.
  METHOD CREATE.
    " Get formatter class name mapped to file type
    DATA LV_OUTPUT_FORMAT   TYPE C LENGTH 4.
    DATA LV_CLASS_NAME TYPE CLASSNAME.

    LV_OUTPUT_FORMAT  = IV_OUTPUT_FORMAT .

    SELECT SINGLE FORMATTER_CLASS
      FROM ZDRS_FM_REGISTRY
      WHERE OUTPUT_FORMAT  = @LV_OUTPUT_FORMAT
        AND IS_ACTIVE = @ABAP_TRUE
      INTO @LV_CLASS_NAME.

    " Fallback mapping for demo/test purposes if registry table is empty
    IF SY-SUBRC <> 0.
      CASE LV_OUTPUT_FORMAT .
        WHEN 'CSV'.
          LV_CLASS_NAME = 'ZCL_CSV_FORMATTER'.
        WHEN 'XLSX'.
          LV_CLASS_NAME = 'ZCL_XLSX_FORMATTER'.
        WHEN OTHERS.
          LV_CLASS_NAME = 'ZCL_CSV_FORMATTER'. " Default
      ENDCASE.
    ENDIF.

    " Dynamic instantiation
    DATA LO_FORMATTER TYPE REF TO OBJECT.
    TRY.
        CREATE OBJECT LO_FORMATTER TYPE (LV_CLASS_NAME).
      CATCH CX_SY_CREATE_OBJECT_ERROR.
        " In case of error, default to CSV if possible
        IF LV_CLASS_NAME <> 'ZCL_CSV_FORMATTER'.
          LV_CLASS_NAME = 'ZCL_CSV_FORMATTER'.
          TRY.
              CREATE OBJECT LO_FORMATTER TYPE (LV_CLASS_NAME).
            CATCH CX_SY_CREATE_OBJECT_ERROR.
              RETURN.
          ENDTRY.
        ENDIF.
    ENDTRY.

    RO_FORMATTER ?= LO_FORMATTER.
  ENDMETHOD.
ENDCLASS.

