CLASS ZCL_SETUP_VALUE_HELP DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES IF_OO_ADT_CLASSRUN.

  PRIVATE SECTION.
    METHODS:
      INSERT_RUN_TYPE
        RAISING CX_SY_OPEN_SQL_DB,
      INSERT_SHIFT_DIRECTION
        RAISING CX_SY_OPEN_SQL_DB,
      INSERT_PERIODIC_GRANULARITY
        RAISING CX_SY_OPEN_SQL_DB,
      INSERT_START_RESTRICTION
        RAISING CX_SY_OPEN_SQL_DB.

ENDCLASS.


CLASS ZCL_SETUP_VALUE_HELP IMPLEMENTATION.

  METHOD IF_OO_ADT_CLASSRUN~MAIN.
    TRY.
        INSERT_RUN_TYPE( ).
        OUT->WRITE( 'zdrs_run_type_vt     → OK' ).

        INSERT_SHIFT_DIRECTION( ).
        OUT->WRITE( 'zdrs_shiftdir_vt     → OK' ).

        INSERT_PERIODIC_GRANULARITY( ).
        OUT->WRITE( 'zdrs_per_gran_vt     → OK' ).

        INSERT_START_RESTRICTION( ).
        OUT->WRITE( 'zdrs_strt_res_vt     → OK' ).

        OUT->WRITE( '--- All tables populated successfully ---' ).

      CATCH CX_SY_OPEN_SQL_DB INTO DATA(LX_DB).
        OUT->WRITE( |DB error: { LX_DB->GET_TEXT( ) }| ).
    ENDTRY.
  ENDMETHOD.


  METHOD INSERT_RUN_TYPE.
    DATA LT_DATA TYPE TABLE OF ZDRS_RUN_TYPE_VT.

    LT_DATA = VALUE #(
      ( CLIENT = SY-MANDT  VALUE = 'I'  RUN_TYPE_TEXT = 'Immediately' )
      ( CLIENT = SY-MANDT  VALUE = 'O'  RUN_TYPE_TEXT = 'Once'        )
      ( CLIENT = SY-MANDT  VALUE = 'P'  RUN_TYPE_TEXT = 'Periodic'    )
    ).

    DELETE FROM ZDRS_RUN_TYPE_VT.
    INSERT ZDRS_RUN_TYPE_VT FROM TABLE @LT_DATA.

    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE CX_SY_OPEN_SQL_DB.
    ENDIF.
  ENDMETHOD.


  METHOD INSERT_SHIFT_DIRECTION.
    DATA LT_DATA TYPE TABLE OF ZDRS_SHIFTDIR_VT.

    LT_DATA = VALUE #(
      ( CLIENT = SY-MANDT  VALUE = '1'  SHIFT_DIR_TEXT = 'Begining of month' )
      ( CLIENT = SY-MANDT  VALUE = '2'  SHIFT_DIR_TEXT = 'Ending of month'   )
    ).

    DELETE FROM ZDRS_SHIFTDIR_VT.
    INSERT ZDRS_SHIFTDIR_VT FROM TABLE @LT_DATA.

    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE CX_SY_OPEN_SQL_DB.
    ENDIF.
  ENDMETHOD.


  METHOD INSERT_PERIODIC_GRANULARITY.
    DATA LT_DATA TYPE TABLE OF ZDRS_PER_GRAN_VT.

    LT_DATA = VALUE #(
      ( CLIENT = SY-MANDT  VALUE = 'MI'  DESCRIPTION = 'Minutes'     )
      ( CLIENT = SY-MANDT  VALUE = 'H'   DESCRIPTION = 'Hours'       )
      ( CLIENT = SY-MANDT  VALUE = 'D'   DESCRIPTION = 'Days'        )
      ( CLIENT = SY-MANDT  VALUE = 'W'   DESCRIPTION = 'Weeks'       )
      ( CLIENT = SY-MANDT  VALUE = 'MO'  DESCRIPTION = 'Months'      )
      ( CLIENT = SY-MANDT  VALUE = 'WM'  DESCRIPTION = 'Week-Months' )
    ).

    DELETE FROM ZDRS_PER_GRAN_VT.
    INSERT ZDRS_PER_GRAN_VT FROM TABLE @LT_DATA.

    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE CX_SY_OPEN_SQL_DB.
    ENDIF.
  ENDMETHOD.


  METHOD INSERT_START_RESTRICTION.
    DATA LT_DATA TYPE TABLE OF ZDRS_STRT_RES_VT.

    LT_DATA = VALUE #(
      ( CLIENT = SY-MANDT  VALUE = 'D'   START_RESTR_TEXT = 'Not process on holiday' )
      ( CLIENT = SY-MANDT  VALUE = 'B'   START_RESTR_TEXT = 'Process before holiday' )
      ( CLIENT = SY-MANDT  VALUE = 'A'   START_RESTR_TEXT = 'Process after holiday'  )
      ( CLIENT = SY-MANDT  VALUE = ' '   START_RESTR_TEXT = 'No restriction'         )
    ).

    DELETE FROM ZDRS_STRT_RES_VT.
    INSERT ZDRS_STRT_RES_VT FROM TABLE @LT_DATA.

    IF SY-SUBRC <> 0.
      RAISE EXCEPTION TYPE CX_SY_OPEN_SQL_DB.
    ENDIF.
  ENDMETHOD.

ENDCLASS.

