CLASS ZCL_CSV_FORMATTER DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES ZIF_FILE_FORMATTER.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS ZCL_CSV_FORMATTER IMPLEMENTATION.

  METHOD ZIF_FILE_FORMATTER~GENERATE.
    RS_RESULT-EXTENSION = 'csv'.
    RS_RESULT-MIME_TYPE = 'text/csv'.

    DATA LV_CSV TYPE STRING.

    " Dereference the data table
    FIELD-SYMBOLS <LT_DATA> TYPE STANDARD TABLE.
    ASSIGN IR_DATA->* TO <LT_DATA>.

    " ── Header row ──
    DATA LV_HDR TYPE STRING.
    LOOP AT IT_COL_META INTO DATA(LS_HCOMP).
      IF LV_HDR IS NOT INITIAL. LV_HDR = LV_HDR && ','. ENDIF.
      LV_HDR = LV_HDR && LS_HCOMP-NAME.
    ENDLOOP.
    LV_CSV = LV_HDR && CL_ABAP_CHAR_UTILITIES=>CR_LF.

    " ── Data rows ──
    LOOP AT <LT_DATA> ASSIGNING FIELD-SYMBOL(<LS_ROW>).
      DATA LV_DROW TYPE STRING.
      CLEAR LV_DROW.
      LOOP AT IT_COL_META INTO DATA(LS_DCOMP).
        IF LV_DROW IS NOT INITIAL. LV_DROW = LV_DROW && ','. ENDIF.
        ASSIGN COMPONENT LS_DCOMP-NAME OF STRUCTURE <LS_ROW> TO FIELD-SYMBOL(<LV_VAL>).
        IF SY-SUBRC = 0. LV_DROW = LV_DROW && |{ <LV_VAL> }|. ENDIF.
      ENDLOOP.
      LV_CSV = LV_CSV && LV_DROW && CL_ABAP_CHAR_UTILITIES=>CR_LF.
    ENDLOOP.

    RS_RESULT-XSTRING = CL_ABAP_CONV_CODEPAGE=>CREATE_OUT( CODEPAGE = `UTF-8` )->CONVERT( LV_CSV ).
  ENDMETHOD.

ENDCLASS.

