CLASS ZCL_REPORT_FACTORY DEFINITION PUBLIC FINAL CREATE PUBLIC.
  PUBLIC SECTION.
    CLASS-METHODS CREATE
      IMPORTING IV_REPORT_ID     TYPE ZDRS_SUBSCR-REPORT_ID
                IS_PARAMS        TYPE ZIF_REPORT=>TY_PARAMS
      RETURNING VALUE(RO_REPORT) TYPE REF TO ZIF_REPORT
      RAISING   CX_APJ_RT.

  PRIVATE SECTION.
    CLASS-METHODS GET_REPORT_CLASS
      IMPORTING IV_REPORT_ID         TYPE ZDRS_SUBSCR-REPORT_ID
      RETURNING VALUE(RV_CLASS_NAME) TYPE CLASSNAME
      RAISING   CX_APJ_RT.
ENDCLASS.

CLASS ZCL_REPORT_FACTORY IMPLEMENTATION.
  METHOD CREATE.
    " 1. Lookup class name from registry
    DATA(LV_CLASS_NAME) = GET_REPORT_CLASS( IV_REPORT_ID ).

    " 2. Guard against invalid configuration
    IF LV_CLASS_NAME IS INITIAL.
      " Message: Report class name is empty
      RAISE EXCEPTION TYPE CX_APJ_RT
        MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
        TYPE 'E'
        NUMBER '035'.
    ENDIF.

    " 3. Dynamic instantiation
    DATA LO_REPORT TYPE REF TO OBJECT.
    TRY.
        CREATE OBJECT LO_REPORT TYPE (LV_CLASS_NAME)
          EXPORTING IS_PARAMS = IS_PARAMS.
      CATCH CX_SY_CREATE_OBJECT_ERROR INTO DATA(LX_OBJ_ERR).
        " Message: Failed to dynamically instantiate report class
        RAISE EXCEPTION TYPE CX_APJ_RT
          MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
          TYPE 'E'
          NUMBER '036'
          EXPORTING
            PREVIOUS = LX_OBJ_ERR.
    ENDTRY.

    " 4. Cast to target interface
    RO_REPORT = CAST ZIF_REPORT( LO_REPORT ).
  ENDMETHOD.

  METHOD GET_REPORT_CLASS.
    SELECT SINGLE REPORT_CLASS
      FROM ZDRS_RP_REGISTRY
      WHERE REPORT_ID = @IV_REPORT_ID
        AND IS_ACTIVE = @ABAP_TRUE
      INTO @RV_CLASS_NAME.

    IF SY-SUBRC <> 0.
      " Message: Report registry entry not found or inactive
      RAISE EXCEPTION TYPE CX_APJ_RT
        MESSAGE ID 'ZMSG_DRS_SP26_SAP01'
        TYPE 'E'
        NUMBER '037'.
    ENDIF.
  ENDMETHOD.
ENDCLASS.

